services:
  backend:
    build:
      context: .
      dockerfile: backend-flock/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb+srv://Emily:oTeqT05STG5XDNXM@cluster0.sdghp.mongodb.net/
      - JWT_SECRET=your_jwt
      - EMAIL_USER=...
      - EMAIL_PASS=...
      - EMAIL_PORT=...
      - EMAIL_HOST=...
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend-flock
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
