FROM node:18 as build

WORKDIR /app
COPY ./frontend-flock/package*.json ./
RUN npm install
COPY ./frontend-flock .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
